In [1]:
%load_ext autoreload
%autoreload 2
import os
import sys
sys.path.append("../libs")
import pandas as pd
from config import DataPath
from data_manager.etf_data_manager import batch_check_etf_data_updated, save_res_df_to_windows, sync_backup, update_etf_data
from data_manager.index_data_manager import batch_check_index_data_updated, update_index_data
from data_manager.providers.etf_list_provider import ETF_LIST
from data_manager.providers.index_list_provider import INDEX_LIST
from fetcher.etf import fund_etf_hist_em, get_all_ETF_fund, get_all_etf_code
from importlib import reload
import datetime
import numpy as np
from proxy.proxy import PROXY_POOL, get_proxy
from data_manager.stock_data_manager import batch_check_stock_data_updated, update_stock_data
from data_manager.providers.stock_list_provider import STOCK_LIST

In [12]:
sync_backup(src=DataPath.DEFAULT_PATH, dest=os.path.join(DataPath.BAK_PATH, "etf_data"))

In [25]:
from data_manager.etf_data_manager import batch_check_etf_data_updated
from data_manager.providers.etf_list_provider import ETF_LIST

symbols = ETF_LIST.get_all_symbol()
status_df = batch_check_etf_data_updated(symbols, target_date="2026-09-09")  # or "2026-04-14"

In [26]:
failed_updated_list = status_df[~status_df["is_updated"]].symbol.tolist()

In [27]:
len(failed_updated_list)

6

In [16]:
update_etf_data(failed_updated_list)

update 159659 in /home/gouzi/projects/invest/data/etf_data/159659.csv
update 159673 in /home/gouzi/projects/invest/data/etf_data/159673.csv
update 159675 in /home/gouzi/projects/invest/data/etf_data/159675.csv
update 159676 in /home/gouzi/projects/invest/data/etf_data/159676.csv
update 159677 in /home/gouzi/projects/invest/data/etf_data/159677.csv
update 159681 in /home/gouzi/projects/invest/data/etf_data/159681.csv
update 159680 in /home/gouzi/projects/invest/data/etf_data/159680.csv
update 159682 in /home/gouzi/projects/invest/data/etf_data/159682.csv
update 159685 in /home/gouzi/projects/invest/data/etf_data/159685.csv
update 159788 in /home/gouzi/projects/invest/data/etf_data/159788.csv
update 159776 in /home/gouzi/projects/invest/data/etf_data/159776.csv
update 159891 in /home/gouzi/projects/invest/data/etf_data/159891.csv
update 159890 in /home/gouzi/projects/invest/data/etf_data/159890.csv
update 511220 in /home/gouzi/projects/invest/data/etf_data/511220.csv
update 511260 in /home/gouzi/projects/invest/data/etf_data/511260.csv
update 511360 in /home/gouzi/projects/invest/data/etf_data/511360.csv
update 511270 in /home/gouzi/projects/invest/data/etf_data/511270.csv
update 511380 in /home/gouzi/projects/invest/data/etf_data/511380.csv
update 511520 in /home/gouzi/projects/invest/data/etf_data/511520.csv
update 512020 in /home/gouzi/projects/invest/data/etf_data/512020.csv
update 511580 in /home/gouzi/projects/invest/data/etf_data/511580.csv
update 512030 in /home/gouzi/projects/invest/data/etf_data/512030.csv
update 512040 in /home/gouzi/projects/invest/data/etf_data/512040.csv
update 512060 in /home/gouzi/projects/invest/data/etf_data/512060.csv
update 512050 in /home/gouzi/projects/invest/data/etf_data/512050.csv
update 512390 in /home/gouzi/projects/invest/data/etf_data/512390.csv
update 512680 in /home/gouzi/projects/invest/data/etf_data/512680.csv
update 512820 in /home/gouzi/projects/invest/data/etf_data/512820.csv
update 512810 in /home/gouzi/projects/invest/data/etf_data/512810.csv
update 512870 in /home/gouzi/projects/invest/data/etf_data/512870.csv
update 512880 in /home/gouzi/projects/invest/data/etf_data/512880.csv
update 513980 in /home/gouzi/projects/invest/data/etf_data/513980.csv
update 512900 in /home/gouzi/projects/invest/data/etf_data/512900.csv
Failed to perform, curl: (56) Connection closed abruptly. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
Failed to perform, curl: (56) Connection closed abruptly. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
update 560650 in /home/gouzi/projects/invest/data/etf_data/560650.csv

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (56) Connection closed abruptly. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/etf_data_manager.py", line 185, in update
    update_df = get_etf_certain_date_data(code, last_update, now)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/etf.py", line 49, in get_etf_certain_date_data
    return fund_etf_hist_em(
           ^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/etf.py", line 95, in fund_etf_hist_em
    r = request_get_via_proxy(url, timeout=15, params=params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.ConnectionError: Failed to perform, curl: (56) Connection closed abruptly. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update 562700 because: Failed to perform, curl: (56) Connection closed abruptly. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
Failed to perform, curl: (56) Connection closed abruptly. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
Failed to perform, curl: (56) Connection closed abruptly. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (56) Connection closed abruptly. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/etf_data_manager.py", line 185, in update
    update_df = get_etf_certain_date_data(code, last_update, now)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/etf.py", line 49, in get_etf_certain_date_data
    return fund_etf_hist_em(
           ^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/etf.py", line 95, in fund_etf_hist_em
    r = request_get_via_proxy(url, timeout=15, params=params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.ConnectionError: Failed to perform, curl: (56) Connection closed abruptly. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update 512000 because: Failed to perform, curl: (56) Connection closed abruptly. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
Failed to perform, curl: (56) Connection closed abruptly. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
Failed to perform, curl: (56) Connection closed abruptly. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
update 562700 in /home/gouzi/projects/invest/data/etf_data/562700.csv
Failed to perform, curl: (56) Connection closed abruptly. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
update 563780 in /home/gouzi/projects/invest/data/etf_data/563780.csv
Failed to perform, curl: (56) Connection closed abruptly. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
update 563900 in /home/gouzi/projects/invest/data/etf_data/563900.csv
update 563890 in /home/gouzi/projects/invest/data/etf_data/563890.csv
update 563980 in /home/gouzi/projects/invest/data/etf_data/563980.csv
update 589350 in /home/gouzi/projects/invest/data/etf_data/589350.csv
Failed to perform, curl: (56) Connection closed abruptly. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
Failed to perform, curl: (56) Connection closed abruptly. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
Failed to load listed ETF symbols due to Failed to fetch ETF spot data after retries, fallback to normal retry
Acquiring data for 515293 for last 4000 days
Failed to load listed ETF symbols due to Failed to fetch ETF spot data after retries, fallback to normal retry
Acquiring data for 516163 for last 4000 days
Can't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IP

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (56) Connection closed abruptly. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/etf_data_manager.py", line 185, in update
    update_df = get_etf_certain_date_data(code, last_update, now)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/etf.py", line 49, in get_etf_certain_date_data
    return fund_etf_hist_em(
           ^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/etf.py", line 95, in fund_etf_hist_em
    r = request_get_via_proxy(url, timeout=15, params=params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.ConnectionError: Failed to perform, curl: (56) Connection closed abruptly. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update 512000 because: Failed to perform, curl: (56) Connection closed abruptly. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
Never do that again, can't execute update with args ('512000',)
Can't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IP

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (56) Connection closed abruptly. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/etf_data_manager.py", line 185, in update
    update_df = get_etf_certain_date_data(code, last_update, now)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/etf.py", line 49, in get_etf_certain_date_data
    return fund_etf_hist_em(
           ^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/etf.py", line 95, in fund_etf_hist_em
    r = request_get_via_proxy(url, timeout=15, params=params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.ConnectionError: Failed to perform, curl: (56) Connection closed abruptly. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update 512010 because: Failed to perform, curl: (56) Connection closed abruptly. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (56) Connection closed abruptly. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/etf_data_manager.py", line 185, in update
    update_df = get_etf_certain_date_data(code, last_update, now)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/etf.py", line 49, in get_etf_certain_date_data
    return fund_etf_hist_em(
           ^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/etf.py", line 95, in fund_etf_hist_em
    r = request_get_via_proxy(url, timeout=15, params=params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.ConnectionError: Failed to perform, curl: (56) Connection closed abruptly. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update 512010 because: Failed to perform, curl: (56) Connection closed abruptly. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
Never do that again, can't execute update with args ('512010',)
Retrying 515293 20250925-20251113 due to Failed to perform, curl: (56) Connection closed abruptly. See https://curl.se/libcurl/c/libcurl-errors.html first for more details., 4 retries left
Retrying 516163 20250309-20250427 due to Failed to perform, curl: (56) Connection closed abruptly. See https://curl.se/libcurl/c/libcurl-errors.html first for more details., 4 retries left
Failed update 515293: fetch failed, will retry
Acquiring data for 515293 for last 4000 days
Failed update 516163: fetch failed, will retry
Acquiring data for 516163 for last 4000 days
Retrying 515293 20240203-20240323 due to Failed to perform, curl: (56) Connection closed abruptly. See https://curl.se/libcurl/c/libcurl-errors.html first for more details., 4 retries left
Retrying 516163 20220802-20220920 due to Failed to perform, curl: (56) Connection closed abruptly. See https://curl.se/libcurl/c/libcurl-errors.html first for more details., 4 retries left
Failed update 515293: fetch failed, will retry
Never do that again, can't execute update with args ('515293',)
Failed update 516163: fetch failed, will retry
Never do that again, can't execute update with args ('516163',)
update 520910 in /home/gouzi/projects/invest/data/etf_data/520910.csv
Successfully updated data for 159659
Successfully updated data for 159673
Successfully updated data for 159675
Successfully updated data for 159676
Successfully updated data for 159677
Successfully updated data for 159680
Successfully updated data for 159681
Successfully updated data for 159682
Successfully updated data for 159685
Successfully updated data for 159776
Successfully updated data for 159788
Successfully updated data for 159890
Successfully updated data for 159891
Successfully updated data for 511220
Successfully updated data for 511260
Successfully updated data for 511270
Successfully updated data for 511360
Successfully updated data for 511380
Successfully updated data for 511520
Successfully updated data for 511580
Failed to update data for 512000
Failed to update data for 512010
Successfully updated data for 512020
Successfully updated data for 512030
Successfully updated data for 512040
Successfully updated data for 512050
Successfully updated data for 512060
Successfully updated data for 512390
Successfully updated data for 512680
Successfully updated data for 512810
Successfully updated data for 512820
Successfully updated data for 512870
Successfully updated data for 512880
Successfully updated data for 512900
Successfully updated data for 513980
Failed to update data for 515293
Failed to update data for 516163
Successfully updated data for 520910
Successfully updated data for 560650
Successfully updated data for 562700
Successfully updated data for 563780
Successfully updated data for 563890
Successfully updated data for 563900
Successfully updated data for 563980
Successfully updated data for 589350

In [7]:
os.makedirs(DataPath.INDEX_PATH, exist_ok=True)
sync_backup(src=DataPath.INDEX_PATH, dest=os.path.join(DataPath.BAK_PATH, "index"))

In [8]:
update_index_data()

Can't get proxy due to Expecting value: line 1 column 1 (char 0), response is 订单提取IP频次超限Can't get proxy due to Expecting value: line 1 column 1 (char 0), response is 订单提取IP频次超限

Can't get proxy due to Expecting value: line 1 column 1 (char 0), response is 订单提取IP频次超限
update 000852 in /home/gouzi/projects/invest/data/index/000852.csv
update 000016 in /home/gouzi/projects/invest/data/index/000016.csv
update 000001 in /home/gouzi/projects/invest/data/index/000001.csv
update 000906 in /home/gouzi/projects/invest/data/index/000906.csv
update 000985 in /home/gouzi/projects/invest/data/index/000985.csv
update 000688 in /home/gouzi/projects/invest/data/index/000688.csv
update 000905 in /home/gouzi/projects/invest/data/index/000905.csv
update 399006 in /home/gouzi/projects/invest/data/index/399006.csv

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (56) Connection closed abruptly. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/index_data_manager.py", line 245, in update
    update_df = _fetch_index_history_in_slices(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/index_data_manager.py", line 205, in _fetch_index_history_in_slices
    return _fetch_index_history(symbol=symbol, start_date=start_date, end_date=end_date)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/index_data_manager.py", line 151, in _fetch_index_history
    return get_index_certain_date_data(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/index.py", line 217, in get_index_certain_date_data
    raise last_error
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/index.py", line 195, in get_index_certain_date_data
    raw_df = _fetch_index_zh_a_hist_raw(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/index.py", line 110, in _fetch_index_zh_a_hist_raw
    response = request_get_via_proxy(url, timeout=15, params=params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.ConnectionError: Failed to perform, curl: (56) Connection closed abruptly. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update 399001 because: Failed to perform, curl: (56) Connection closed abruptly. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (56) Connection closed abruptly. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/index_data_manager.py", line 245, in update
    update_df = _fetch_index_history_in_slices(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/index_data_manager.py", line 205, in _fetch_index_history_in_slices
    return _fetch_index_history(symbol=symbol, start_date=start_date, end_date=end_date)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/index_data_manager.py", line 151, in _fetch_index_history
    return get_index_certain_date_data(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/index.py", line 217, in get_index_certain_date_data
    raise last_error
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/index.py", line 195, in get_index_certain_date_data
    raw_df = _fetch_index_zh_a_hist_raw(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/index.py", line 110, in _fetch_index_zh_a_hist_raw
    response = request_get_via_proxy(url, timeout=15, params=params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.ConnectionError: Failed to perform, curl: (56) Connection closed abruptly. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update 000300 because: Failed to perform, curl: (56) Connection closed abruptly. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
Successfully updated data for 000001
Failed to update data for 399001
Successfully updated data for 399006
Successfully updated data for 000688
Successfully updated data for 000016
Failed to update data for 000300
Successfully updated data for 000905
Successfully updated data for 000852
Successfully updated data for 000906
Successfully updated data for 000985

In [9]:
index_symbols = INDEX_LIST.get_all_symbol()
index_status_df = batch_check_index_data_updated(index_symbols, target_date=None)
failed_index_update_list = index_status_df[~index_status_df["is_updated"]].symbol.tolist()
index_status_df

   symbol  exists last_local_date target_date  is_updated
0  000300    True      2026-09-08  2026-09-09       False
1  399001    True      2026-09-07  2026-09-09       False
2  000001    True      2026-09-09  2026-09-09        True
3  000016    True      2026-09-09  2026-09-09        True
4  000688    True      2026-09-09  2026-09-09        True
5  000852    True      2026-09-09  2026-09-09        True
6  000905    True      2026-09-09  2026-09-09        True
7  000906    True      2026-09-09  2026-09-09        True
8  000985    True      2026-09-09  2026-09-09        True
9  399006    True      2026-09-09  2026-09-09        True

In [10]:
failed_index_update_list

['000300', '399001']

In [11]:
update_index_data(failed_index_update_list)

Can't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IP
Can't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IP
Can't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IP
Can't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IP
Can't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IP
Can't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IP
Can't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IPCan't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IP

Can't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IP
Can't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IP
ProxyPool init failed for hailiang: Failed to acquire proxies after max retries
ProxyPool init failed for hailiang: Failed to acquire proxies after max retries
Can't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IP
Can't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IP
Can't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IPCan't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IP

Can't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IP
Can't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IP
Can't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IPCan't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IP

Can't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IP
Can't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IP
Can't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IPCan't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IP

Can't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IPCan't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IP

Can't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IPCan't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IP

Can't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IPCan't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IP

Can't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IPCan't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IP

Can't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IPCan't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IP

Can't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IP
Can't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IP
Can't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IP
Can't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IP
Can't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IP
Can't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IP
Can't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IP
Can't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IP

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/index_data_manager.py", line 245, in update
    update_df = _fetch_index_history_in_slices(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/index_data_manager.py", line 205, in _fetch_index_history_in_slices
    return _fetch_index_history(symbol=symbol, start_date=start_date, end_date=end_date)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/index_data_manager.py", line 151, in _fetch_index_history
    return get_index_certain_date_data(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/index.py", line 217, in get_index_certain_date_data
    raise last_error
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/index.py", line 195, in get_index_certain_date_data
    raw_df = _fetch_index_zh_a_hist_raw(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/index.py", line 110, in _fetch_index_zh_a_hist_raw
    response = request_get_via_proxy(url, timeout=15, params=params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 51, in request_get_via_proxy
    proxy = get_proxy()
            ^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/proxy/proxy.py", line 633, in get_proxy
    return PROXY_POOL.get_proxy()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/proxy/proxy.py", line 602, in get_proxy
    return self._get_pool().get_proxy()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/proxy/proxy.py", line 514, in get_proxy
    self.refresh()
  File "/home/gouzi/projects/invest/notebooks/../libs/proxy/proxy.py", line 550, in refresh
    self.pool = self._get_proxies()
                ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/proxy/proxy.py", line 506, in _get_proxies
    return self._fetch_proxies_from_api()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/proxy/proxy.py", line 437, in _fetch_proxies_from_api
    raise RuntimeError("Failed to acquire proxies after max retries")
RuntimeError: Failed to acquire proxies after max retries

Can't update 399001 because: Failed to acquire proxies after max retries

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/index_data_manager.py", line 245, in update
    update_df = _fetch_index_history_in_slices(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/index_data_manager.py", line 205, in _fetch_index_history_in_slices
    return _fetch_index_history(symbol=symbol, start_date=start_date, end_date=end_date)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/index_data_manager.py", line 151, in _fetch_index_history
    return get_index_certain_date_data(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/index.py", line 217, in get_index_certain_date_data
    raise last_error
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/index.py", line 195, in get_index_certain_date_data
    raw_df = _fetch_index_zh_a_hist_raw(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/index.py", line 110, in _fetch_index_zh_a_hist_raw
    response = request_get_via_proxy(url, timeout=15, params=params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 51, in request_get_via_proxy
    proxy = get_proxy()
            ^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/proxy/proxy.py", line 633, in get_proxy
    return PROXY_POOL.get_proxy()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/proxy/proxy.py", line 602, in get_proxy
    return self._get_pool().get_proxy()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/proxy/proxy.py", line 514, in get_proxy
    self.refresh()
  File "/home/gouzi/projects/invest/notebooks/../libs/proxy/proxy.py", line 550, in refresh
    self.pool = self._get_proxies()
                ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/proxy/proxy.py", line 506, in _get_proxies
    return self._fetch_proxies_from_api()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/proxy/proxy.py", line 437, in _fetch_proxies_from_api
    raise RuntimeError("Failed to acquire proxies after max retries")
RuntimeError: Failed to acquire proxies after max retries

Can't update 000300 because: Failed to acquire proxies after max retries
Failed to update data for 000300
Failed to update data for 399001

## 更新A股股票数据

In [28]:
os.makedirs(DataPath.STOCK_PATH, exist_ok=True)
sync_backup(src=DataPath.STOCK_PATH, dest=os.path.join(DataPath.BAK_PATH, "stock_data"))

In [31]:
from data_manager.stock_data_manager import batch_check_stock_data_updated
from data_manager.providers.stock_list_provider import STOCK_LIST

stock_symbols = STOCK_LIST.get_all_symbol()
stock_status_df = batch_check_stock_data_updated(stock_symbols, target_date="2026-09-09") # or "2026-04-14"
stock_status_df

      symbol  exists last_local_date target_date  is_updated
0     000001    True      2026-09-08  2026-09-09       False
1     000002    True      2026-09-08  2026-09-09       False
2     000006    True      2026-09-08  2026-09-09       False
3     000016    True      2026-09-03  2026-09-09       False
4     000035    True      2026-09-07  2026-09-09       False
...      ...     ...             ...         ...         ...
5350  688819    True      2026-09-09  2026-09-09        True
5351  688820    True      2026-09-09  2026-09-09        True
5352  688825    True      2026-09-09  2026-09-09        True
5353  688981    True      2026-09-09  2026-09-09        True
5354  689009    True      2026-09-09  2026-09-09        True

[5355 rows x 5 columns]

In [32]:
failed_stock_list = stock_status_df[~stock_status_df["is_updated"]].symbol.tolist()
len(failed_stock_list)

201

In [33]:
update_stock_data(failed_stock_list)

update 000001 in /home/gouzi/projects/invest/data/stock_data/000001.csv
update 000002 in /home/gouzi/projects/invest/data/stock_data/000002.csv
update 000006 in /home/gouzi/projects/invest/data/stock_data/000006.csv
update 000016 in /home/gouzi/projects/invest/data/stock_data/000016.csv
update 000035 in /home/gouzi/projects/invest/data/stock_data/000035.csv
update 000036 in /home/gouzi/projects/invest/data/stock_data/000036.csv
update 000037 in /home/gouzi/projects/invest/data/stock_data/000037.csv
update 000338 in /home/gouzi/projects/invest/data/stock_data/000338.csv
update 000400 in /home/gouzi/projects/invest/data/stock_data/000400.csv
update 000401 in /home/gouzi/projects/invest/data/stock_data/000401.csv
update 000506 in /home/gouzi/projects/invest/data/stock_data/000506.csv
update 000514 in /home/gouzi/projects/invest/data/stock_data/000514.csv
update 000504 in /home/gouzi/projects/invest/data/stock_data/000504.csv
update 000505 in /home/gouzi/projects/invest/data/stock_data/000505.csv
update 000568 in /home/gouzi/projects/invest/data/stock_data/000568.csv
update 000570 in /home/gouzi/projects/invest/data/stock_data/000570.csv
update 000571 in /home/gouzi/projects/invest/data/stock_data/000571.csv
update 000573 in /home/gouzi/projects/invest/data/stock_data/000573.csv
update 000516 in /home/gouzi/projects/invest/data/stock_data/000516.csv
update 000572 in /home/gouzi/projects/invest/data/stock_data/000572.csv
update 000576 in /home/gouzi/projects/invest/data/stock_data/000576.csv
update 000567 in /home/gouzi/projects/invest/data/stock_data/000567.csv
update 000623 in /home/gouzi/projects/invest/data/stock_data/000623.csv
update 000581 in /home/gouzi/projects/invest/data/stock_data/000581.csv
update 000629 in /home/gouzi/projects/invest/data/stock_data/000629.csv
update 000625 in /home/gouzi/projects/invest/data/stock_data/000625.csv
update 000630 in /home/gouzi/projects/invest/data/stock_data/000630.csv
update 000620 in /home/gouzi/projects/invest/data/stock_data/000620.csv
update 000626 in /home/gouzi/projects/invest/data/stock_data/000626.csv
update 000633 in /home/gouzi/projects/invest/data/stock_data/000633.csv
update 000720 in /home/gouzi/projects/invest/data/stock_data/000720.csv
update 000628 in /home/gouzi/projects/invest/data/stock_data/000628.csv
update 000719 in /home/gouzi/projects/invest/data/stock_data/000719.csv
update 000721 in /home/gouzi/projects/invest/data/stock_data/000721.csv
update 002731 in /home/gouzi/projects/invest/data/stock_data/002731.csv
update 300527 in /home/gouzi/projects/invest/data/stock_data/300527.csv
update 002038 in /home/gouzi/projects/invest/data/stock_data/002038.csv
update 002870 in /home/gouzi/projects/invest/data/stock_data/002870.csv
update 300597 in /home/gouzi/projects/invest/data/stock_data/300597.csv
update 002478 in /home/gouzi/projects/invest/data/stock_data/002478.csv
update 002998 in /home/gouzi/projects/invest/data/stock_data/002998.csv
update 301139 in /home/gouzi/projects/invest/data/stock_data/301139.csv
update 300525 in /home/gouzi/projects/invest/data/stock_data/300525.csv
update 600077 in /home/gouzi/projects/invest/data/stock_data/600077.csv
update 600068 in /home/gouzi/projects/invest/data/stock_data/600068.csv
update 600083 in /home/gouzi/projects/invest/data/stock_data/600083.csv
update 600090 in /home/gouzi/projects/invest/data/stock_data/600090.csv
update 600069 in /home/gouzi/projects/invest/data/stock_data/600069.csv
update 600086 in /home/gouzi/projects/invest/data/stock_data/600086.csv
update 600070 in /home/gouzi/projects/invest/data/stock_data/600070.csv
update 600001 in /home/gouzi/projects/invest/data/stock_data/600001.csv
update 600091 in /home/gouzi/projects/invest/data/stock_data/600091.csv
update 600074 in /home/gouzi/projects/invest/data/stock_data/600074.csv
update 600190 in /home/gouzi/projects/invest/data/stock_data/600190.csv
update 600145 in /home/gouzi/projects/invest/data/stock_data/600145.csv
update 600193 in /home/gouzi/projects/invest/data/stock_data/600193.csv
update 600002 in /home/gouzi/projects/invest/data/stock_data/600002.csv
update 600200 in /home/gouzi/projects/invest/data/stock_data/600200.csv
update 600146 in /home/gouzi/projects/invest/data/stock_data/600146.csv
update 600102 in /home/gouzi/projects/invest/data/stock_data/600102.csv
update 600209 in /home/gouzi/projects/invest/data/stock_data/600209.csv
update 600112 in /home/gouzi/projects/invest/data/stock_data/600112.csv
update 600213 in /home/gouzi/projects/invest/data/stock_data/600213.csv
update 600175 in /home/gouzi/projects/invest/data/stock_data/600175.csv
update 600122 in /home/gouzi/projects/invest/data/stock_data/600122.csv
update 600087 in /home/gouzi/projects/invest/data/stock_data/600087.csv
update 600092 in /home/gouzi/projects/invest/data/stock_data/600092.csv
update 600220 in /home/gouzi/projects/invest/data/stock_data/600220.csv
update 600225 in /home/gouzi/projects/invest/data/stock_data/600225.csv
update 600139 in /home/gouzi/projects/invest/data/stock_data/600139.csv
update 600260 in /home/gouzi/projects/invest/data/stock_data/600260.csv
update 600240 in /home/gouzi/projects/invest/data/stock_data/600240.csv
update 600277 in /home/gouzi/projects/invest/data/stock_data/600277.csv
update 600205 in /home/gouzi/projects/invest/data/stock_data/600205.csv
update 600093 in /home/gouzi/projects/invest/data/stock_data/600093.csv
update 600421 in /home/gouzi/projects/invest/data/stock_data/600421.csv
update 600003 in /home/gouzi/projects/invest/data/stock_data/600003.csv
update 600242 in /home/gouzi/projects/invest/data/stock_data/600242.csv
update 600317 in /home/gouzi/projects/invest/data/stock_data/600317.csv
update 600385 in /home/gouzi/projects/invest/data/stock_data/600385.csv
update 600321 in /home/gouzi/projects/invest/data/stock_data/600321.csv
update 600387 in /home/gouzi/projects/invest/data/stock_data/600387.csv
update 600355 in /home/gouzi/projects/invest/data/stock_data/600355.csv
update 600247 in /home/gouzi/projects/invest/data/stock_data/600247.csv
update 600432 in /home/gouzi/projects/invest/data/stock_data/600432.csv
update 600393 in /home/gouzi/projects/invest/data/stock_data/600393.csv
update 600462 in /home/gouzi/projects/invest/data/stock_data/600462.csv
update 600005 in /home/gouzi/projects/invest/data/stock_data/600005.csv
update 600181 in /home/gouzi/projects/invest/data/stock_data/600181.csv
update 600263 in /home/gouzi/projects/invest/data/stock_data/600263.csv
update 600466 in /home/gouzi/projects/invest/data/stock_data/600466.csv
update 600286 in /home/gouzi/projects/invest/data/stock_data/600286.csv
update 600296 in /home/gouzi/projects/invest/data/stock_data/600296.csv
update 600555 in /home/gouzi/projects/invest/data/stock_data/600555.csv
update 600290 in /home/gouzi/projects/invest/data/stock_data/600290.csv
update 600636 in /home/gouzi/projects/invest/data/stock_data/600636.csv
update 600253 in /home/gouzi/projects/invest/data/stock_data/600253.csv
update 600565 in /home/gouzi/projects/invest/data/stock_data/600565.csv
update 600270 in /home/gouzi/projects/invest/data/stock_data/600270.csv
update 600297 in /home/gouzi/projects/invest/data/stock_data/600297.csv
update 600291 in /home/gouzi/projects/invest/data/stock_data/600291.csv
update 600401 in /home/gouzi/projects/invest/data/stock_data/600401.csv
update 600275 in /home/gouzi/projects/invest/data/stock_data/600275.csv
update 600357 in /home/gouzi/projects/invest/data/stock_data/600357.csv
update 600705 in /home/gouzi/projects/invest/data/stock_data/600705.csv
update 600607 in /home/gouzi/projects/invest/data/stock_data/600607.csv
update 600656 in /home/gouzi/projects/invest/data/stock_data/600656.csv
update 600627 in /home/gouzi/projects/invest/data/stock_data/600627.csv
update 600608 in /home/gouzi/projects/invest/data/stock_data/600608.csv
Can't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IP
update 600591 in /home/gouzi/projects/invest/data/stock_data/600591.csv
update 600599 in /home/gouzi/projects/invest/data/stock_data/600599.csv
update 600614 in /home/gouzi/projects/invest/data/stock_data/600614.csv
update 600672 in /home/gouzi/projects/invest/data/stock_data/600672.csv
update 600836 in /home/gouzi/projects/invest/data/stock_data/600836.csv
update 600695 in /home/gouzi/projects/invest/data/stock_data/600695.csv
update 600752 in /home/gouzi/projects/invest/data/stock_data/600752.csv
update 600837 in /home/gouzi/projects/invest/data/stock_data/600837.csv
update 600772 in /home/gouzi/projects/invest/data/stock_data/600772.csv
update 600696 in /home/gouzi/projects/invest/data/stock_data/600696.csv
update 600631 in /home/gouzi/projects/invest/data/stock_data/600631.csv
update 600709 in /home/gouzi/projects/invest/data/stock_data/600709.csv
update 600677 in /home/gouzi/projects/invest/data/stock_data/600677.csv
update 600659 in /home/gouzi/projects/invest/data/stock_data/600659.csv
update 600472 in /home/gouzi/projects/invest/data/stock_data/600472.csv
update 600723 in /home/gouzi/projects/invest/data/stock_data/600723.csv
update 600781 in /home/gouzi/projects/invest/data/stock_data/600781.csv
update 600306 in /home/gouzi/projects/invest/data/stock_data/600306.csv
update 600680 in /home/gouzi/projects/invest/data/stock_data/600680.csv
update 600799 in /home/gouzi/projects/invest/data/stock_data/600799.csvupdate 600646 in /home/gouzi/projects/invest/data/stock_data/600646.csv

update 600311 in /home/gouzi/projects/invest/data/stock_data/600311.csv
update 600485 in /home/gouzi/projects/invest/data/stock_data/600485.csv
update 600804 in /home/gouzi/projects/invest/data/stock_data/600804.csv
update 600747 in /home/gouzi/projects/invest/data/stock_data/600747.csv
update 600813 in /home/gouzi/projects/invest/data/stock_data/600813.csv
update 600647 in /home/gouzi/projects/invest/data/stock_data/600647.csv
update 600840 in /home/gouzi/projects/invest/data/stock_data/600840.csv
update 600823 in /home/gouzi/projects/invest/data/stock_data/600823.csv
update 600532 in /home/gouzi/projects/invest/data/stock_data/600532.csv
update 600762 in /home/gouzi/projects/invest/data/stock_data/600762.csv
update 600825 in /home/gouzi/projects/invest/data/stock_data/600825.csv
update 600890 in /home/gouzi/projects/invest/data/stock_data/600890.csv
update 600766 in /home/gouzi/projects/invest/data/stock_data/600766.csv
update 600806 in /home/gouzi/projects/invest/data/stock_data/600806.csv
update 600652 in /home/gouzi/projects/invest/data/stock_data/600652.csv
update 600891 in /home/gouzi/projects/invest/data/stock_data/600891.csv
update 600811 in /home/gouzi/projects/invest/data/stock_data/600811.csv
update 600700 in /home/gouzi/projects/invest/data/stock_data/600700.csv
update 600767 in /home/gouzi/projects/invest/data/stock_data/600767.csv
update 601028 in /home/gouzi/projects/invest/data/stock_data/601028.csv
update 600786 in /home/gouzi/projects/invest/data/stock_data/600786.csv
update 600669 in /home/gouzi/projects/invest/data/stock_data/600669.csv
update 600896 in /home/gouzi/projects/invest/data/stock_data/600896.csv
update 601258 in /home/gouzi/projects/invest/data/stock_data/601258.csv
update 600701 in /home/gouzi/projects/invest/data/stock_data/600701.csv
update 600898 in /home/gouzi/projects/invest/data/stock_data/600898.csv
update 601558 in /home/gouzi/projects/invest/data/stock_data/601558.csv
Retrying 600687 20230224-20240223 due to Failed to perform, curl: (56) Connection closed abruptly. See https://curl.se/libcurl/c/libcurl-errors.html first for more details., 4 retries left
update 600842 in /home/gouzi/projects/invest/data/stock_data/600842.csv
update 600553 in /home/gouzi/projects/invest/data/stock_data/600553.csv
update 605577 in /home/gouzi/projects/invest/data/stock_data/605577.csv
update 600852 in /home/gouzi/projects/invest/data/stock_data/600852.csv
update 601989 in /home/gouzi/projects/invest/data/stock_data/601989.csv
update 688432 in /home/gouzi/projects/invest/data/stock_data/688432.csv
update 600832 in /home/gouzi/projects/invest/data/stock_data/600832.csv
update 603133 in /home/gouzi/projects/invest/data/stock_data/603133.csv
update 603603 in /home/gouzi/projects/invest/data/stock_data/603603.csv
update 603003 in /home/gouzi/projects/invest/data/stock_data/603003.csv
update 600625 in /home/gouzi/projects/invest/data/stock_data/600625.csv
update 603963 in /home/gouzi/projects/invest/data/stock_data/603963.csv
update 603056 in /home/gouzi/projects/invest/data/stock_data/603056.csv
update 688086 in /home/gouzi/projects/invest/data/stock_data/688086.csv
update 688287 in /home/gouzi/projects/invest/data/stock_data/688287.csv
update 600856 in /home/gouzi/projects/invest/data/stock_data/600856.csv
update 688291 in /home/gouzi/projects/invest/data/stock_data/688291.csv
update 600687 in /home/gouzi/projects/invest/data/stock_data/600687.csv
update 603157 in /home/gouzi/projects/invest/data/stock_data/603157.csv
update 603388 in /home/gouzi/projects/invest/data/stock_data/603388.csv
update 603996 in /home/gouzi/projects/invest/data/stock_data/603996.csv
update 688555 in /home/gouzi/projects/invest/data/stock_data/688555.csv
update 605081 in /home/gouzi/projects/invest/data/stock_data/605081.csv
update 600870 in /home/gouzi/projects/invest/data/stock_data/600870.csv
update 603555 in /home/gouzi/projects/invest/data/stock_data/603555.csv
update 601268 in /home/gouzi/projects/invest/data/stock_data/601268.csv
update 600899 in /home/gouzi/projects/invest/data/stock_data/600899.csv
update 600632 in /home/gouzi/projects/invest/data/stock_data/600632.csv
update 600929 in /home/gouzi/projects/invest/data/stock_data/600929.csv
update 600788 in /home/gouzi/projects/invest/data/stock_data/600788.csv
update 600670 in /home/gouzi/projects/invest/data/stock_data/600670.csv
update 600978 in /home/gouzi/projects/invest/data/stock_data/600978.csv
update 600634 in /home/gouzi/projects/invest/data/stock_data/600634.csv
Retrying 900950 19920101-19921230 due to Failed to perform, curl: (56) Connection closed abruptly. See https://curl.se/libcurl/c/libcurl-errors.html first for more details., 4 retries left
update 600878 in /home/gouzi/projects/invest/data/stock_data/600878.csv
update 600991 in /home/gouzi/projects/invest/data/stock_data/600991.csv
update 601299 in /home/gouzi/projects/invest/data/stock_data/601299.csv
Can't get proxy due to Expecting value: line 1 column 1 (char 0), response is 您提取且未使用的IP太多，请优先使用已经提取的IP
update 600065 in /home/gouzi/projects/invest/data/stock_data/600065.csv
Retrying 900950 19920101-19921230 due to Failed to perform, curl: (56) Connection closed abruptly. See https://curl.se/libcurl/c/libcurl-errors.html first for more details., 3 retries left
Successfully updated data for 000001
Successfully updated data for 000002
Successfully updated data for 000006
Successfully updated data for 000016
Successfully updated data for 000035
Successfully updated data for 000036
Successfully updated data for 000037
Successfully updated data for 000338
Successfully updated data for 000400
Successfully updated data for 000401
Successfully updated data for 000504
Successfully updated data for 000505
Successfully updated data for 000506
Successfully updated data for 000514
Successfully updated data for 000516
Successfully updated data for 000567
Successfully updated data for 000568
Successfully updated data for 000570
Successfully updated data for 000571
Successfully updated data for 000572
Successfully updated data for 000573
Successfully updated data for 000576
Successfully updated data for 000581
Successfully updated data for 000620
Successfully updated data for 000623
Successfully updated data for 000625
Successfully updated data for 000626
Successfully updated data for 000628
Successfully updated data for 000629
Successfully updated data for 000630
Successfully updated data for 000633
Successfully updated data for 000719
Successfully updated data for 000720
Successfully updated data for 000721
Successfully updated data for 002038
Successfully updated data for 002478
Successfully updated data for 002731
Successfully updated data for 002870
Successfully updated data for 002998
Successfully updated data for 300525
Successfully updated data for 300527
Successfully updated data for 300597
Successfully updated data for 301139
Successfully updated data for 600001
Successfully updated data for 600002
Successfully updated data for 600003
Successfully updated data for 600005
Successfully updated data for 600065
Successfully updated data for 600068
Successfully updated data for 600069
Successfully updated data for 600070
Successfully updated data for 600074
Successfully updated data for 600077
Successfully updated data for 600083
Successfully updated data for 600086
Successfully updated data for 600087
Successfully updated data for 600090
Successfully updated data for 600091
Successfully updated data for 600092
Successfully updated data for 600093
Successfully updated data for 600102
Successfully updated data for 600112
Successfully updated data for 600122
Successfully updated data for 600139
Successfully updated data for 600145
Successfully updated data for 600146
Successfully updated data for 600175
Successfully updated data for 600181
Successfully updated data for 600190
Successfully updated data for 600193
Successfully updated data for 600200
Successfully updated data for 600205
Successfully updated data for 600209
Successfully updated data for 600213
Successfully updated data for 600220
Successfully updated data for 600225
Successfully updated data for 600240
Successfully updated data for 600242
Successfully updated data for 600247
Successfully updated data for 600253
Successfully updated data for 600260
Successfully updated data for 600263
Successfully updated data for 600270
Successfully updated data for 600275
Successfully updated data for 600277
Successfully updated data for 600286
Successfully updated data for 600290
Successfully updated data for 600291
Successfully updated data for 600296
Successfully updated data for 600297
Successfully updated data for 600306
Successfully updated data for 600311
Successfully updated data for 600317
Successfully updated data for 600321
Successfully updated data for 600355
Successfully updated data for 600357
Successfully updated data for 600385
Successfully updated data for 600387
Successfully updated data for 600393
Successfully updated data for 600401
Successfully updated data for 600421
Successfully updated data for 600432
Successfully updated data for 600462
Successfully updated data for 600466
Successfully updated data for 600472
Successfully updated data for 600485
Successfully updated data for 600532
Successfully updated data for 600553
Successfully updated data for 600555
Successfully updated data for 600565
Successfully updated data for 600591
Successfully updated data for 600599
Successfully updated data for 600607
Successfully updated data for 600608
Successfully updated data for 600614
Successfully updated data for 600625
Successfully updated data for 600627
Successfully updated data for 600631
Successfully updated data for 600632
Successfully updated data for 600634
Successfully updated data for 600636
Successfully updated data for 600646
Successfully updated data for 600647
Successfully updated data for 600652
Successfully updated data for 600656
Successfully updated data for 600659
Successfully updated data for 600669
Successfully updated data for 600670
Successfully updated data for 600672
Successfully updated data for 600677
Successfully updated data for 600680
Successfully updated data for 600687
Successfully updated data for 600695
Successfully updated data for 600696
Successfully updated data for 600700
Successfully updated data for 600701
Successfully updated data for 600705
Successfully updated data for 600709
Successfully updated data for 600723
Successfully updated data for 600747
Successfully updated data for 600752
Successfully updated data for 600762

## 更新A股市值/股本数据 (daily_basic)

In [21]:
os.makedirs(DataPath.DAILY_BASIC_PATH, exist_ok=True)
sync_backup(src=DataPath.DAILY_BASIC_PATH, dest=os.path.join(DataPath.BAK_PATH, "daily_basic"))

In [22]:
from data_manager.daily_basic_manager import batch_check_daily_basic_updated, update_daily_basic

basic_symbols = STOCK_LIST.get_all_symbol()
daily_basic_status_df = batch_check_daily_basic_updated(basic_symbols, target_date=None) # or "2026-04-14"
daily_basic_status_df

      symbol  exists last_local_date target_date  is_updated
0     000001    True      2026-09-08  2026-09-09       False
1     000002    True      2026-09-08  2026-09-09       False
2     000006    True      2026-09-08  2026-09-09       False
3     000007    True      2026-09-08  2026-09-09       False
4     000008    True      2026-09-08  2026-09-09       False
...      ...     ...             ...         ...         ...
5350  900950   False            None  2026-09-09        True
5351  900951   False            None  2026-09-09        True
5352  900953   False            None  2026-09-09        True
5353  900956   False            None  2026-09-09        True
5354  900957   False            None  2026-09-09        True

[5355 rows x 5 columns]

In [23]:
failed_basic_list = daily_basic_status_df[~daily_basic_status_df["is_updated"]].symbol.tolist()
len(failed_basic_list)

5202

In [24]:
update_daily_basic(failed_basic_list)

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000001 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000498 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000002 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000501 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000006 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000503 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000007 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000504 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000008 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000505 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000009 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000506 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000010 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000507 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000011 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000509 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000012 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000510 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 300811 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000014 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000513 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 300812 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000016 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000514 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 300813 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000017 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000516 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3001 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3001 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 300814 because: Failed to perform, curl: (28) Connection timed out after 3001 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000019 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000517 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 300815 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000020 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000518 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 300816 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000021 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3001 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3001 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000519 because: Failed to perform, curl: (28) Connection timed out after 3001 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 300817 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000025 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000520 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 300818 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000026 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000521 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 300819 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000027 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000523 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 300820 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000028 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000524 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 300821 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000029 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000525 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 300822 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000030 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000526 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 300823 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000031 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000528 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000032 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000529 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000034 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000530 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000035 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000531 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000536 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000045 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000537 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000048 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000538 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000049 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000539 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000050 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000541 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000055 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000543 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000056 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000544 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000058 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000545 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000059 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000546 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000060 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000547 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000061 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3001 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3001 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000548 because: Failed to perform, curl: (28) Connection timed out after 3001 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000062 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000550 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000063 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000551 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000065 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000552 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3001 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3001 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000066 because: Failed to perform, curl: (28) Connection timed out after 3001 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000553 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000068 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000554 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000069 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000555 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000070 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000557 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000078 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000558 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3001 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3001 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000088 because: Failed to perform, curl: (28) Connection timed out after 3001 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000559 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000089 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000560 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000090 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3001 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3001 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000561 because: Failed to perform, curl: (28) Connection timed out after 3001 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000096 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000563 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000099 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000564 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000100 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000565 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000151 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000566 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000153 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3001 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3001 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000567 because: Failed to perform, curl: (28) Connection timed out after 3001 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000155 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000568 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000156 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000570 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000157 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000571 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000158 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000572 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000159 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000573 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000166 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 732, in _request_once
    c.perform()
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 505, in perform
    self._check_error(ret, "perform")
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/curl.py", line 269, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gouzi/projects/invest/notebooks/../libs/data_manager/daily_basic_manager.py", line 224, in update_daily_basic_symbol
    new_rows = get_stock_daily_basic_em(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/stock.py", line 215, in get_stock_daily_basic_em
    r = request_get_via_proxy(_STOCK_DAILY_BASIC_FILE_URL, timeout=20, params=params, max_proxy_retries=3)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 70, in request_get_via_proxy
    raise last_err
  File "/home/gouzi/projects/invest/notebooks/../libs/fetcher/utils.py", line 54, in request_get_via_proxy
    response = requests.get(
               ^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 148, in get
    return request(method="GET", url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/__init__.py", line 140, in request
    return s.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 795, in request
    return self._request_once(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/gouzi/projects/invest/.venv/lib/python3.12/site-packages/curl_cffi/requests/session.py", line 739, in _request_once
    raise error(str(e), e.code, rsp) from e
curl_cffi.requests.exceptions.Timeout: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

Can't update daily_basic for 000576 because: Failed to perform, curl: (28) Connection timed out after 3000 milliseconds. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
Failed to update daily_basic for 000001
Failed to update daily_basic for 000002
Failed to update daily_basic for 000006
Failed to update daily_basic for 000007
Failed to update daily_basic for 000008
Failed to update daily_basic for 000009
Failed to update daily_basic for 000010
Failed to update daily_basic for 000011
Failed to update daily_basic for 000012
Failed to update daily_basic for 000014
Failed to update daily_basic for 000016
Failed to update daily_basic for 000017
Failed to update daily_basic for 000019
Failed to update daily_basic for 000020
Failed to update daily_basic for 000021
Failed to update daily_basic for 000025
Failed to update daily_basic for 000026
Failed to update daily_basic for 000027
Failed to update daily_basic for 000028
Failed to update daily_basic for 000029
Failed to update daily_basic for 000030
Failed to update daily_basic for 000031
Failed to update daily_basic for 000032
Failed to update daily_basic for 000034
Failed to update daily_basic for 000035
Failed to update daily_basic for 000036
Failed to update daily_basic for 000037
Failed to update daily_basic for 000039
Failed to update daily_basic for 000042
Failed to update daily_basic for 000045
Failed to update daily_basic for 000048
Failed to update daily_basic for 000049
Failed to update daily_basic for 000050
Failed to update daily_basic for 000055
Failed to update daily_basic for 000056
Failed to update daily_basic for 000058
Failed to update daily_basic for 000059
Failed to update daily_basic for 000060
Failed to update daily_basic for 000061
Failed to update daily_basic for 000062
Failed to update daily_basic for 000063
Failed to update daily_basic for 000065
Failed to update daily_basic for 000066
Failed to update daily_basic for 000068
Failed to update daily_basic for 000069
Failed to update daily_basic for 000070
Failed to update daily_basic for 000078
Failed to update daily_basic for 000088
Failed to update daily_basic for 000089
Failed to update daily_basic for 000090
Failed to update daily_basic for 000096
Failed to update daily_basic for 000099
Failed to update daily_basic for 000100
Failed to update daily_basic for 000151
Failed to update daily_basic for 000153
Failed to update daily_basic for 000155
Failed to update daily_basic for 000156
Failed to update daily_basic for 000157
Failed to update daily_basic for 000158
Failed to update daily_basic for 000159
Failed to update daily_basic for 000166
Failed to update daily_basic for 000498
Failed to update daily_basic for 000501
Failed to update daily_basic for 000503
Failed to update daily_basic for 000504
Failed to update daily_basic for 000505
Failed to update daily_basic for 000506
Failed to update daily_basic for 000507
Failed to update daily_basic for 000509
Failed to update daily_basic for 000510
Failed to update daily_basic for 000513
Failed to update daily_basic for 000514
Failed to update daily_basic for 000516
Failed to update daily_basic for 000517
Failed to update daily_basic for 000518
Failed to update daily_basic for 000519
Failed to update daily_basic for 000520
Failed to update daily_basic for 000521
Failed to update daily_basic for 000523
Failed to update daily_basic for 000524
Failed to update daily_basic for 000525
Failed to update daily_basic for 000526
Failed to update daily_basic for 000528
Failed to update daily_basic for 000529
Failed to update daily_basic for 000530
Failed to update daily_basic for 000531
Failed to update daily_basic for 000532
Failed to update daily_basic for 000533
Failed to update daily_basic for 000534
Failed to update daily_basic for 000536
Failed to update daily_basic for 000537
Failed to update daily_basic for 000538
Failed to update daily_basic for 000539
Failed to update daily_basic for 000541
Failed to update daily_basic for 000543
Failed to update daily_basic for 000544
Failed to update daily_basic for 000545
Failed to update daily_basic for 000546
Failed to update daily_basic for 000547
Failed to update daily_basic for 000548
Failed to update daily_basic for 000550
Failed to update daily_basic for 000551
Failed to update daily_basic for 000552
Failed to update daily_basic for 000553
Failed to update daily_basic for 000554
Failed to update daily_basic for 000555
Failed to update daily_basic for 000557
Failed to update daily_basic for 000558
Failed to update daily_basic for 000559
Failed to update daily_basic for 000560
Failed to update daily_basic for 000561
Failed to update daily_basic for 000563
Failed to update daily_basic for 000564
Failed to update daily_basic for 000565
Failed to update daily_basic for 000566
Failed to update daily_basic for 000567
Failed to update daily_basic for 000568
Failed to update daily_basic for 000570
Failed to update daily_basic for 000571
Failed to update daily_basic for 000572
Failed to update daily_basic for 000573
Failed to update daily_basic for 000576
Failed to update daily_basic for 300811
Failed to update daily_basic for 300812
Failed to update daily_basic for 300813
Failed to update daily_basic for 300814
Failed to update daily_basic for 300815
Failed to update daily_basic for 300816
Failed to update daily_basic for 300817
Failed to update daily_basic for 300818
Failed to update daily_basic for 300819
Failed to update daily_basic for 300820
Failed to update daily_basic for 300821
Failed to update daily_basic for 300822
Failed to update daily_basic for 300823

[('000001', False),
 ('000002', False),
 ('000006', False),
 ('000007', False),
 ('000008', False),
 ('000009', False),
 ('000010', False),
 ('000011', False),
 ('000012', False),
 ('000014', False),
 ('000016', False),
 ('000017', False),
 ('000019', False),
 ('000020', False),
 ('000021', False),
 ('000025', False),
 ('000026', False),
 ('000027', False),
 ('000028', False),
 ('000029', False),
 ('000030', False),
 ('000031', False),
 ('000032', False),
 ('000034', False),
 ('000035', False),
 ('000036', False),
 ('000037', False),
 ('000039', False),
 ('000042', False),
 ('000045', False),
 ('000048', False),
 ('000049', False),
 ('000050', False),
 ('000055', False),
 ('000056', False),
 ('000058', False),
 ('000059', False),
 ('000060', False),
 ('000061', False),
 ('000062', False),
 ('000063', False),
 ('000065', False),
 ('000066', False),
 ('000068', False),
 ('000069', False),
 ('000070', False),
 ('000078', False),
 ('000088', False),
 ('000089', False),
 ('000090', False),
 ('000096', False),
 ('000099', False),
 ('000100', False),
 ('000151', False),
 ('000153', False),
 ('000155', False),
 ('000156', False),
 ('000157', False),
 ('000158', False),
 ('000159', False),
 ('000166', False),
 ('000301', True),
 ('000333', True),
 ('000338', True),
 ('000400', True),
 ('000401', True),
 ('000402', True),
 ('000403', True),
 ('000404', True),
 ('000407', True),
 ('000408', True),
 ('000409', True),
 ('000410', True),
 ('000411', True),
 ('000415', True),
 ('000417', True),
 ('000419', True),
 ('000420', True),
 ('000421', True),
 ('000422', True),
 ('000423', True),
 ('000425', True),
 ('000426', True),
 ('000428', True),
 ('000429', True),
 ('000430', True),
 ('000488', True),
 ('000498', False),
 ('000501', False),
 ('000503', False),
 ('000504', False),
 ('000505', False),
 ('000506', False),
 ('000507', False),
 ('000509', False),
 ('000510', False),
 ('000513', False),
 ('000514', False),
 ('000516', False),
 ('000517', False),
 ('000518', False),
 ('000519', False),
 ('000520', False),
 ('000521', False),
 ('000523', False),
 ('000524', False),
 ('000525', False),
 ('000526', False),
 ('000528', False),
 ('000529', False),
 ('000530', False),
 ('000531', False),
 ('000532', False),
 ('000533', False),
 ('000534', False),
 ('000536', False),
 ('000537', False),
 ('000538', False),
 ('000539', False),
 ('000541', False),
 ('000543', False),
 ('000544', False),
 ('000545', False),
 ('000546', False),
 ('000547', False),
 ('000548', False),
 ('000550', False),
 ('000551', False),
 ('000552', False),
 ('000553', False),
 ('000554', False),
 ('000555', False),
 ('000557', False),
 ('000558', False),
 ('000559', False),
 ('000560', False),
 ('000561', False),
 ('000563', False),
 ('000564', False),
 ('000565', False),
 ('000566', False),
 ('000567', False),
 ('000568', False),
 ('000570', False),
 ('000571', False),
 ('000572', False),
 ('000573', False),
 ('000576', False),
 ('000581', True),
 ('000582', True),
 ('000586', True),
 ('000589', True),
 ('000590', True),
 ('000591', True),
 ('000592', True),
 ('000593', True),
 ('000595', True),
 ('000596', True),
 ('000597', True),
 ('000598', True),
 ('000599', True),
 ('000600', True),
 ('000601', True),
 ('000603', True),
 ('000605', True),
 ('000607', True),
 ('000608', True),
 ('000609', True),
 ('000610', True),
 ('000612', True),
 ('000615', True),
 ('000617', True),
 ('000619', True),
 ('000620', True),
 ('000623', True),
 ('000625', True),
 ('000626', True),
 ('000628', True),
 ('000629', True),
 ('000630', True),
 ('000631', True),
 ('000632', True),
 ('000633', True),
 ('000635', True),
 ('000636', True),
 ('000637', True),
 ('000639', True),
 ('000650', True),
 ('000651', True),
 ('000652', True),
 ('000655', True),
 ('000656', True),
 ('000657', True),
 ('000659', True),
 ('000661', True),
 ('000663', True),
 ('000665', True),
 ('000668', True),
 ('000669', True),
 ('000670', True),
 ('000672', True),
 ('000676', True),
 ('000677', True),
 ('000678', True),
 ('000679', True),
 ('000680', True),
 ('000681', True),
 ('000682', True),
 ('000683', True),
 ('000685', True),
 ('000686', True),
 ('000688', True),
 ('000690', True),
 ('000691', True),
 ('000692', True),
 ('000695', True),
 ('000697', True),
 ('000698', True),
 ('000700', True),
 ('000701', True),
 ('000702', True),
 ('000703', True),
 ('000705', True),
 ('000707', True),
 ('000708', True),
 ('000709', True),
 ('000710', True),
 ('000711', True),
 ('000712', True),
 ('000713', True),
 ('000715', True),
 ('000716', True),
 ('000717', True),
 ('000718', True),
 ('000719', True),
 ('000720', True),
 ('000721', True),
 ('000722', True),
 ('000723', True),
 ('000725', True),
 ('000726', True),
 ('000727', True),
 ('000728', True),
 ('000729', True),
 ('000731', True),
 ('000733', True),
 ('000735', True),
 ('000736', True),
 ('000737', True),
 ('000738', True),
 ('000739', True),
 ('000750', True),
 ('000751', True),
 ('000752', True),
 ('000753', True),
 ('000755', True),
 ('000756', True),
 ('000757', True),
 ('000758', True),
 ('000759', True),
 ('000761', True),
 ('000762', True),
 ('000766', True),
 ('000767', True),
 ('000768', True),
 ('000776', True),
 ('000777', True),
 ('000778', True),
 ('000779', True),
 ('000782', True),
 ('000783', True),
 ('000785', True),
 ('000786', True),
 ('000788', True),
 ('000789', True),
 ('000790', True),
 ('000791', True),
 ('000792', True),
 ('000793', True),
 ('000795', True),
 ('000796', True),
 ('000797', True),
 ('000798', True),
 ('000799', True),
 ('000800', True),
 ('000801', True),
 ('000802', True),
 ('000803', True),
 ('000807', True),
 ('000809', True),
 ('000810', True),
 ('000811', True),
 ('000812', True),
 ('000813', True),
 ('000815', True),
 ('000816', True),
 ('000818', True),
 ('000819', True),
 ('000820', True),
 ('000821', True),
 ('000822', True),
 ('000823', True),
 ('000825', True),
 ('000826', True),
 ('000828', True),
 ('000829', True),
 ('000830', True),
 ('000831', True),
 ('000833', True),
 ('000837', True),
 ('000838', True),
 ('000839', True),
 ('000848', True),
 ('000850', True),
 ('000852', True),
 ('000856', True),
 ('000858', True),
 ('000859', True),
 ('000860', True),
 ('000862', True),
 ('000863', True),
 ('000868', True),
 ('000869', True),
 ('000875', True),
 ('000876', True),
 ('000877', True),
 ('000878', True),
 ('000880', True),
 ('000881', True),
 ('000882', True),
 ('000883', True),
 ('000885', True),
 ('000886', True),
 ('000887', True),
 ('000888', True),
 ('000889', True),
 ('000890', True),
 ('000892', True),
 ('000893', True),
 ('000895', True),
 ('000897', True),
 ('000898', True),
 ('000899', True),
 ('000900', True),
 ('000901', True),
 ('000902', True),
 ('000903', True),
 ('000905', True),
 ('000906', True),
 ('000908', True),
 ('000909', True),
 ('000910', True),
 ('000911', True),
 ('000912', True),
 ('000913', True),
 ('000915', True),
 ('000917', True),
 ('000919', True),
 ('000920', True),
 ('000921', True),
 ('000922', True),
 ('000923', True),
 ('000925', True),
 ('000926', True),
 ('000927', True),
 ('000928', True),
 ('000929', True),
 ('000930', True),
 ('000931', True),
 ('000932', True),
 ('000933', True),
 ('000935', True),
 ('000936', True),
 ('000937', True),
 ('000938', True),
 ('000948', True),
 ('000949', True),
 ('000950', True),
 ('000951', True),
 ('000952', True),
 ('000953', True),
 ('000955', True),
 ('000957', True),
 ('000958', True),
 ('000959', True),
 ('000960', True),
 ('000962', True),
 ('000963', True),
 ('000965', True),
 ('000966', True),
 ('000967', True),
 ('000968', True),
 ('000969', True),
 ('000970', True),
 ('000972', True),
 ('000973', True),
 ('000975', True),
 ('000977', True),
 ('000978', True),
 ('000980', True),
 ('000981', True),
 ('000983', True),
 ('000985', True),
 ('000987', True),
 ('000988', True),
 ('000989', True),
 ('000990', True),
 ('000993', True),
 ('000995', True),
 ('000997', True),
 ('000998', True),
 ('000999', True),
 ('001201', True),
 ('001202', True),
 ('001203', True),
 ('001205', True),
 ('001206', True),
 ('001207', True),
 ('001208', True),
 ('001209', True),
 ('001210', True),
 ('001211', True),
 ('001212', True),
 ('001213', True),
 ('001215', True),
 ('001216', True),
 ('001217', True),
 ('001218', True),
 ('001219', True),
 ('001220', True),
 ('001221', True),
 ('001222', True),
 ('001223', True),
 ('001225', True),
 ('001226', True),
 ('001227', True),
 ('001228', True),
 ('001229', True),
 ('001230', True),
 ('001231', True),
 ('001233', True),
 ('001234', True),
 ('001236', True),
 ('001237', True),
 ('001238', True),
 ('001239', True),
 ('001248', True),
 ('001255', True),
 ('001256', True),
 ('001257', True),
 ('001258', True),
 ('001259', True),
 ('001260', True),
 ('001266', True),
 ('001267', True),
 ('001268', True),
 ('001269', True),
 ('001270', True),
 ('001277', True),
 ('001278', True),
 ('001279', True),
 ('001280', True),
 ('001282', True),
 ('001283', True),
 ('001285', True),
 ('001286', True),
 ('001287', True),
 ('001288', True),
 ('001289', True),
 ('001296', True),
 ('001298', True),
 ('001299', True),
 ('001300', True),
 ('001301', True),
 ('001306', True),
 ('001308', True),
 ('001309', True),
 ('001311', True),
 ('001312', True),
 ('001313', True),
 ('001314', True),
 ('001316', True),
 ('001317', True),
 ('001318', True),
 ('001319', True),
 ('001322', True),
 ('001323', True),
 ('001324', True),
 ('001325', True),
 ('001326', True),
 ('001328', True),
 ('001330', True),
 ('001331', True),
 ('001332', True),
 ('001333', True),
 ('001335', True),
 ('001336', True),
 ('001337', True),
 ('001338', True),
 ('001339', True),
 ('001356', True),
 ('001358', True),
 ('001359', True),
 ('001360', True),
 ('001365', True),
 ('001366', True),
 ('001367', True),
 ('001368', True),
 ('001369', True),
 ('001373', True),
 ('001376', True),
 ('001378', True),
 ('001379', True),
 ('001380', True),
 ('001382', True),
 ('001386', True),
 ('001387', True),
 ('001388', True),
 ('001389', True),
 ('001390', True),
 ('001391', True),
 ('001393', True),
 ('001395', True),
 ('001396', True),
 ('001399', True),
 ('001400', True),
 ('001696', True),
 ('001872', True),
 ('001896', True),
 ('001914', True),
 ('001965', True),
 ('001979', True),
 ('002001', True),
 ('002003', True),
 ('002004', True),
 ('002005', True),
 ('002006', True),
 ('002007', True),
 ('002008', True),
 ('002009', True),
 ('002010', True),
 ('002011', True),
 ('002012', True),
 ('002014', True),
 ('002015', True),
 ('002016', True),
 ('002017', True),
 ('002019', True),
 ('002020', True),
 ('002021', True),
 ('002022', True),
 ('002023', True),
 ('002024', True),
 ('002025', True),
 ('002026', True),
 ('002027', True),
 ('002028', True),
 ('002029', True),
 ('002030', True),
 ('002031', True),
 ('002032', True),
 ('002033', True),
 ('002034', True),
 ('002035', True),
 ('002036', True),
 ('002037', True),
 ('002038', True),
 ('002039', True),
 ('002040', True),
 ('002041', True),
 ('002042', True),
 ('002043', True),
 ('002044', True),
 ('002045', True),
 ('002046', True),
 ('002047', True),
 ('002048', True),
 ('002049', True),
 ('002050', True),
 ('002051', True),
 ('002052', True),
 ('002053', True),
 ('002054', True),
 ('002055', True),
 ('002056', True),
 ('002057', True),
 ('002058', True),
 ('002059', True),
 ('002060', True),
 ('002061', True),
 ('002062', True),
 ('002063', True),
 ('002064', True),
 ('002065', True),
 ('002066', True),
 ('002067', True),
 ('002068', True),
 ('002069', True),
 ('002072', True),
 ('002073', True),
 ('002074', True),
 ('002075', True),
 ('002076', True),
 ('002077', True),
 ('002078', True),
 ('002079', True),
 ('002080', True),
 ('002081', True),
 ('002082', True),
 ('002083', True),
 ('002084', True),
 ('002085', True),
 ('002086', True),
 ('002088', True),
 ('002090', True),
 ('002091', True),
 ('002092', True),
 ('002093', True),
 ('002094', True),
 ('002095', True),
 ('002096', True),
 ('002097', True),
 ('002098', True),
 ('002099', True),
 ('002100', True),
 ('002101', True),
 ('002102', True),
 ('002103', True),
 ('002104', True),
 ('002105', True),
 ('002106', True),
 ('002107', True),
 ('002108', True),
 ('002109', True),
 ('002110', True),
 ('002111', True),
 ('002112', True),
 ('002114', True),
 ('002115', True),
 ('002116', True),
 ('002117', True),
 ('002119', True),
 ('002120', True),
 ('002121', True),
 ('002122', True),
 ('002123', True),
 ('002124', True),
 ('002125', True),
 ('002126', True),
 ('002127', True),
 ('002128', True),
 ('002129', True),
 ('002130', True),
 ('002131', True),
 ('002132', True),
 ('002133', True),
 ('002134', True),
 ('002135', True),
 ('002136', True),
 ('002137', True),
 ('002138', True),
 ('002139', True),
 ('002140', True),
 ('002141', True),
 ('002142', True),
 ('002144', True),
 ('002145', True),
 ('002146', True),
 ('002148', True),
 ('002149', True),
 ('002150', True),
 ('002151', True),
 ('002152', True),
 ('002153', True),
 ('002154', True),
 ('002155', True),
 ('002156', True),
 ('002157', True),
 ('002158', True),
 ('002159', True),
 ('002160', True),
 ('002161', True),
 ('002162', True),
 ('002163', True),
 ('002164', True),
 ('002165', True),
 ('002166', True),
 ('002167', True),
 ('002168', True),
 ('002169', True),
 ('002170', True),
 ('002171', True),
 ('002172', True),
 ('002173', True),
 ('002174', True),
 ('002175', True),
 ('002176', True),
 ('002177', True),
 ('002178', True),
 ('002179', True),
 ('002180', True),
 ('002181', True),
 ('002182', True),
 ('002183', True),
 ('002184', True),
 ('002185', True),
 ('002186', True),
 ('002187', True),
 ('002188', True),
 ('002189', True),
 ('002190', True),
 ('002191', True),
 ('002192', True),
 ('002193', True),
 ('002194', True),
 ('002195', True),
 ('002196', True),
 ('002197', True),
 ('002198', True),
 ('002199', True),
 ('002200', True),
 ('002201', True),
 ('002202', True),
 ('002203', True),
 ('002204', True),
 ('002205', True),
 ('002206', True),
 ('002207', True),
 ('002208', True),
 ('002209', True),
 ('002210', True),
 ('002211', True),
 ('002212', True),
 ('002213', True),
 ('002214', True),
 ('002215', True),
 ('002216', True),
 ('002217', True),
 ('002218', True),
 ('002219', True),
 ('002221', True),
 ('002222', True),
 ('002223', True),
 ('002224', True),
 ('002225', True),
 ('002226', True),
 ('002227', True),
 ('002228', True),
 ('002229', True),
 ('002230', True),
 ('002232', True),
 ('002233', True),
 ('002234', True),
 ('002235', True),
 ('002236', True),
 ('002237', True),
 ('002238', True),
 ('002239', True),
 ('002240', True),
 ('002241', True),
 ('002242', True),
 ('002243', True),
 ('002244', True),
 ('002245', True),
 ('002246', True),
 ('002247', True),
 ('002248', True),
 ('002249', True),
 ('002250', True),
 ('002251', True),
 ('002252', True),
 ('002253', True),
 ('002254', True),
 ('002255', True),
 ('002256', True),
 ('002258', True),
 ('002259', True),
 ('002261', True),
 ('002262', True),
 ('002263', True),
 ('002264', True),
 ('002265', True),
 ('002266', True),
 ('002267', True),
 ('002268', True),
 ('002269', True),
 ('002270', True),
 ('002271', True),
 ('002272', True),
 ('002273', True),
 ('002274', True),
 ('002275', True),
 ('002276', True),
 ('002277', True),
 ('002278', True),
 ('002279', True),
 ('002281', True),
 ('002282', True),
 ('002283', True),
 ('002284', True),
 ('002285', True),
 ('002286', True),
 ('002287', True),
 ('002289', True),
 ('002290', True),
 ('002291', True),
 ('002292', True),
 ('002293', True),
 ('002294', True),
 ('002295', True),
 ('002296', True),
 ('002297', True),
 ('002298', True),
 ('002299', True),
 ('002300', True),
 ('002301', True),
 ('002302', True),
 ('002303', True),
 ('002304', True),
 ('002305', True),
 ('002306', True),
 ('002307', True),
 ('002309', True),
 ('002310', True),
 ('002311', True),
 ('002312', True),
 ('002313', True),
 ('002314', True),
 ('002315', True),
 ('002316', True),
 ('002317', True),
 ('002318', True),
 ('002319', True),
 ('002320', True),
 ('002321', True),
 ('002322', True),
 ('002323', True),
 ('002324', True),
 ('002326', True),
 ('002327', True),
 ('002328', True),
 ('002329', True),
 ('002330', True),
 ('002331', True),
 ('002332', True),
 ('002333', True),
 ('002334', True),
 ('002335', True),
 ('002337', True),
 ('002338', True),
 ('002339', True),
 ('002340', True),
 ('002342', True),
 ('002343', True),
 ('002344', True),
 ('002345', True),
 ('002346', True),
 ('002347', True),
 ('002348', True),
 ('002349', True),
 ('002350', True),
 ('002351', True),
 ('002352', True),
 ('002353', True),
 ('002354', True),
 ('002355', True),
 ('002356', True),
 ('002357', True),
 ('002358', True),
 ('002360', True),
 ('002361', True),
 ('002362', True),
 ('002363', True),
 ('002364', True),
 ('002365', True),
 ('002366', True),
 ('002367', True),
 ('002368', True),
 ('002369', True),
 ('002370', True),
 ('002371', True),
 ('002372', True),
 ('002373', True),
 ('002374', True),
 ('002375', True),
 ('002376', True),
 ('002377', True),
 ('002378', True),
 ('002379', True),
 ('002380', True),
 ('002381', True),
 ('002382', True),
 ('002383', True),
 ('002384', True),
 ('002385', True),
 ('002386', True),
 ('002387', True),
 ('002388', True),
 ('002389', True),
 ('002390', True),
 ('002391', True),
 ('002392', True),
 ('002393', True),
 ('002394', True),
 ('002395', True),
 ('002396', True),
 ('002397', True),
 ('002398', True),
 ('002399', True),
 ('002400', True),
 ('002401', True),
 ('002402', True),
 ('002403', True),
 ('002404', True),
 ('002405', True),
 ('002406', True),
 ('002407', True),
 ('002408', True),
 ('002409', True),
 ('002410', True),
 ('002412', True),
 ('002413', True),
 ('002414', True),
 ('002415', True),
 ('002416', True),
 ('002418', True),
 ('002419', True),
 ('002420', True),
 ('002421', True),
 ('002422', True),
 ('002423', True),
 ('002424', True),
 ('002425', True),
 ('002426', True),
 ('002427', True),
 ('002428', True),
 ('002429', True),
 ('002430', True),
 ('002431', True),
 ('002432', True),
 ('002434', True),
 ('002436', True),
 ('002437', True),
 ('002438', True),
 ('002439', True),
 ('002440', True),
 ('002441', True),
 ('002442', True),
 ('002443', True),
 ('002444', True),
 ('002445', True),
 ('002446', True),
 ('002448', True),
 ('002449', True),
 ('002451', True),
 ('002452', True),
 ('002453', True),
 ('002454', True),
 ('002455', True),
 ('002456', True),
 ('002457', True),
 ('002458', True),
 ('002459', True),
 ('002460', True),
 ('002461', True),
 ('002462', True),
 ('002463', True),
 ('002465', True),
 ('002466', True),
 ('002467', True),
 ('002468', True),
 ('002469', True),
 ('002470', True),
 ('002471', True),
 ('002472', True),
 ('002474', True),
 ('002475', True),
 ('002476', True),
 ('002478', True),
 ('002479', True),
 ('002480', True),
 ('002481', True),
 ('002482', True),
 ('002483', True),
 ('002484', True),
 ('002485', True),
 ('002486', True),
 ('002487', True),
 ('002488', True),
 ('002489', True),
 ('002490', True),
 ('002491', True),
 ('002492', True),
 ('002493', True),
 ('002494', True),
 ('002495', True),
 ('002496', True),
 ('002497', True),
 ('002498', True),
 ('002500', True),
 ...]